apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: assistentes-gpt
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    - api.assistentes-gpt.oondemand.online
    - assistentes-gpt.oondemand.online
